### ISSUE TITLE
Frames > Polaroid > Curvature Setting

### ISSUE THREAD

**Issue by GMICFan** [GreycLab/gmic#20]
Hello,

Thank you for such an awesome project!

I have not been able to use the (Curvature) setting when using this frame filter. 

Having all settings to (0), and only using the (Y-shadow) to around 3, and setting the (Smoothness), and wanting to set a (Curvature) for the shadow, it will not adjust the shadow's curvature like before. The last version of GMIC that I was able to use the curvature setting was 3.2.6.

Thank you for your help.

**Comment by dtschump** [comment]
Hello, thanks for reporting this issue.
It should be fixed with : https://github.com/GreycLab/gmic/commit/850f84115f6a596894c0ff758758d8b1ebb8acc2

I'm currently uploading the fix on the G'MIC server. It should be ready in a few minutes, after you press the "Update Filters" button, from the plug-in interface. A new parameter "Y-curvature" has been added, as shown below:

![image](https://github.com/GreycLab/gmic/assets/10114565/4ea42e63-d255-4ff3-9c9c-51630fff28f3)
