### ISSUE TITLE
GMIC-Qt Crashes Krita when attempting to update filter definitions

### ISSUE THREAD

**Issue by DragonWizard23** [GreycLab/gmic#35]
Hello,
GMIC-Qt has been crashing Krita when I try to update the filter definitions. I'm not sure how to get a crash log, but I'm happy to provide as much information as I can to reproduce the issue. 

1. Create a new document in Krita, it can be anything. I've had the crash with a 1024x1024 16-bit float file and with a 100x100 8-bit integer one too, so I don't think the file size is the problem. 
2. Select filters and then choose the option that says start GMIC-Qt from the drop-down menu. 
3. Tick the checkbox for internet on the GMIC menu that appears. 
4. Click the button to update filter definitions. 
5. *It takes a moment, says filters have been updated, then crashes.*

I'm running Krita 5.2.2 without plugins on Windows 11. I've allocated approximately 14 of my 16 GB of RAM, and I don't have a discrete graphics card.

**Comment by dtschump** [comment]
Hello, thanks for reporting the issue.

Unfortunately, the G'MIC-Qt plug-in for Krita is a special version, maintained by the Krita developers, so I'm afraid there's not much we can do to help right away. The G'MIC-Qt version provided in Krita is now relatively old, and it's possible that this bug has already been fixed on our side. I suggest you make a bug report directly to the Krita developers, who will hopefully be able to help you further (and maybe make them want to upgrade to the latest G'MIC version 3.3.3 to see if the bug is still there :) ).
Cheers,

David.

**Comment by dtschump** [comment]
That could be interesting to report the bug on the Krita bugtracker. There is a "gmic" section if I remember well.

**Comment by DragonWizard23** [comment]
I would report it, but I don't have any email aliases other than my github one, which unfortunately doesn't forward emails and I prefer not to expose my primary email address. However, you are more than welcome to report the bug, if you would like. :)
