### ISSUE TITLE
Copy Bug.

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/gmic#85]
Just leaving this here.

```
foo:
eval "v=vector(#50);
 copy(v[0],0,25,2,1);
 print(v);"
```
Result:
```
C:\Windows\System32>gmic foo
[gmic]./ Start G'MIC interpreter (v.3.5.0).
[gmic_math_parser] v = (uninitialized) (mem[36]: vector50)
[gmic_math_parser] v = [ 0,0,1,0,2,0,3,0,4,0,5,0,6,0,7,0,8,0,9,0,10,0,-1,0,-2,0,-3,0,-4,0,-5,0,0.5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 ] (size: 50)
[gmic]./ End G'MIC interpreter.
```

The end should have 24 on v[-2]. I don't think I have seen this before, I'm doing this to copy into a huge array.

**Comment by dtschump** [comment]
The result is actually correct.
I'm not sure what you expected here, but `copy(v[0],0,25,2,1)` does not means  `repeat (25,k, v[2*k] = k)`.
It copies the content of the internal math parser memory from adress 0 to address 24 (with an increment of 1), to the address starting at `v[0]`  (with an increment of 2).
As the first values in the internal parser memory are actually usual constants (0...10 and -1..-5, and so on), that's why you get what you get.
Now : 
- If you need to set 0 every even index : `copy(v[0],0,25,2,0)`.
- If you need to have a sequence of increasing values every even index : `v = expr('x%2?0:x/2',50)`

**Comment by Reptorian1125** [comment]
That is what I was expecting as I used it like that before. But, now I know that these are addresses, which explains why `copy(addr(const_value))` changes the const value. That being said, I think I found my solution to one of my issues for now.
